
name: Ejecutar pruebas Selenium JUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar proyecto
        run: mvn clean compile

      - name: Ejecutar pruebas
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn test