
name: Ejecutar pruebas Selenium JUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

          # Crear enlace simbólico que Selenium espera
          sudo mkdir -p /opt/google/chrome
          [ "$(readlink -f /opt/google/chrome/google-chrome)" != "/usr/bin/google-chrome" ] && sudo ln -sf /usr/bin/google-chrome /opt/google/chrome/google-chrome || echo "Symlink already correct"

      - name: Set DISPLAY variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests with Maven
        run: mvn test

      - name: Instalar Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generar reporte Allure
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report